### ISSUE TITLE
`libstdc++-6.dll` dependency is missing while running `zarb.exe`

### ISSUE THREAD

**Issue by Stonica** [zarbchain/zarb.network#25]
I ran `zarb.exe` on windows 10 but it nagged `libstdc++-6.dll` is missing, I think it is a Mingw dll.

**Comment by b00f** [comment]
@Stonica Thanks for bringing this issue up 
this should be addressed at our latest release [v1.0.1](https://github.com/zarbchain/zarb-go/releases/tag/v1.0.1)

Please use main repo so your issues won't be missed out and orginized
thanks.
